{"name": "困人处置列表-未知", "status": "passed", "attachments": [{"name": "log", "source": "ccddfc48-b9f2-4852-b0c6-d1e67bbb4b53-attachment.txt", "type": "text/plain"}], "start": 1690529620815, "stop": 1690529621073, "uuid": "145c75c8-7ea1-4d11-b3a6-4d5efbc9dcf3", "historyId": "c16e0aac483c5cc5ea4df007421ff869", "testCaseId": "8649210a73733792a7b60d9aac38ca04", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_008", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "11532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}