{"name": "困人处置列表-未知", "status": "passed", "attachments": [{"name": "log", "source": "ae47da7f-1fb1-4fe4-8ddd-bc4a7a3054e3-attachment.txt", "type": "text/plain"}], "start": 1692349415123, "stop": 1692349415369, "uuid": "e1982ddd-7b61-47fe-8f98-fae440bf180f", "historyId": "c16e0aac483c5cc5ea4df007421ff869", "testCaseId": "8649210a73733792a7b60d9aac38ca04", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_008", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "7716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}