{"name": "困人处置列表-区域外困人", "status": "passed", "attachments": [{"name": "log", "source": "7d4251f8-ef73-468a-8b99-1c414a0f3aba-attachment.txt", "type": "text/plain"}], "start": 1692236260237, "stop": 1692236260479, "uuid": "54b14ba5-3191-410f-9d01-17c3abb14d6e", "historyId": "c2dcd89c85259072fed7c872065f3930", "testCaseId": "c1a6e2a4541e010d83d870c732449350", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_007", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "13776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}