{"name": "困人处置列表导出", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not subscriptable", "trace": ">   ???\nE   TypeError: 'NoneType' object is not subscriptable\n\nD:\\work\\jishiyu\\Interface_Test\\test_case\\opsPC\\conftest.py:10: TypeError"}, "start": 1692597242968, "stop": 1692597242968, "uuid": "14d6b17a-043b-4ec6-adef-893f83ba8b90", "historyId": "30a8c3a4ab4509baa6acb33cb056b9dd", "testCaseId": "cef688bb25ca2940c863587f9bf05023", "fullName": "opsPC.test_emergency#test_device_error_trapped_export_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "14852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}