{"name": "困人处置列表-未知", "status": "passed", "attachments": [{"name": "log", "source": "0575ad80-d3b1-47bf-bd8e-ef497a40ad25-attachment.txt", "type": "text/plain"}], "start": 1692236260481, "stop": 1692236260747, "uuid": "89cd400a-7cb7-4326-8809-ecf446acbad5", "historyId": "c16e0aac483c5cc5ea4df007421ff869", "testCaseId": "8649210a73733792a7b60d9aac38ca04", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_008", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "13776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}