{"name": "困人处置列表-误报", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not subscriptable", "trace": ">   ???\nE   TypeError: 'NoneType' object is not subscriptable\n\nD:\\work\\jishiyu\\Interface_Test\\test_case\\opsPC\\conftest.py:10: TypeError"}, "start": 1692597242938, "stop": 1692597242938, "uuid": "619678e0-a079-46c7-b712-c19c02b623c7", "historyId": "b6df9803d2bc4b21784f5a63eb51f738", "testCaseId": "dc6b56f404a99f8f9a0366f36753c0b5", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_004", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "14852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}