{"name": "一键呼救统计-传入错误的参数值", "status": "passed", "attachments": [{"name": "log", "source": "ca512abe-f9e0-45c4-8bf2-94882216bd30-attachment.txt", "type": "text/plain"}], "start": 1692236268759, "stop": 1692236268794, "uuid": "dbd64c5f-ee95-41b4-9dc1-556c2f9d9fd1", "historyId": "58d53ee22002b9b497e4d451f228f041", "testCaseId": "2dcd49077c70bc638412cf395f619231", "fullName": "opsPC.test_homePage#test_callRecord_count_003", "labels": [{"name": "story", "value": "首页"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_homePage"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "13776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_homePage"}]}