{"name": "困人处置列表-未知", "status": "passed", "attachments": [{"name": "log", "source": "98460e56-5e07-4bb7-ad64-d739b1942695-attachment.txt", "type": "text/plain"}], "start": 1692069125657, "stop": 1692069125906, "uuid": "50ae7558-f6b4-4f36-880e-2b59c29255c9", "historyId": "c16e0aac483c5cc5ea4df007421ff869", "testCaseId": "8649210a73733792a7b60d9aac38ca04", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_008", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "14880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}