{"name": "困人处置列表-未知", "status": "passed", "attachments": [{"name": "log", "source": "92beef81-b9b0-482d-a3d6-0556767d6b09-attachment.txt", "type": "text/plain"}], "start": 1690436277774, "stop": 1690436278031, "uuid": "2c9a4f94-1e2a-490c-ae38-80e578e41608", "historyId": "c16e0aac483c5cc5ea4df007421ff869", "testCaseId": "8649210a73733792a7b60d9aac38ca04", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_008", "labels": [{"name": "story", "value": "应急处置"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "10244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}