{"name": "困人处置列表-未知", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not subscriptable", "trace": ">   ???\nE   TypeError: 'NoneType' object is not subscriptable\n\nD:\\work\\jishiyu\\Interface_Test\\test_case\\opsPC\\conftest.py:10: TypeError"}, "start": 1692597242961, "stop": 1692597242961, "uuid": "23227961-a497-495a-9736-e5da65b336e1", "historyId": "c16e0aac483c5cc5ea4df007421ff869", "testCaseId": "8649210a73733792a7b60d9aac38ca04", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_008", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "14852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}